version: '3'
services:
  words-app:
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    environment:
      - DB_ENDPOINT=mongodb
    depends_on:
      - "mongodb"
  mongodb:
    image: "mongo"
